name: pide_ya_mobile
description: App de Repartidor para Pide Ya - EscÃ¡ner de Lealtad.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core
  supabase_flutter: ^2.0.0
  provider: ^6.1.1
  mobile_scanner: ^3.5.0
  google_fonts: ^6.1.0
  intl: ^0.18.1
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.0
  shimmer: ^3.0.0
  shared_preferences: ^2.2.0
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  screenshot: ^3.0.0
  geolocator: ^14.0.2
  http: ^1.6.0
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
